//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planer
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public int Sort { get; set; }
        public string Description { get; set; }
    }
}
